name: Test
on: push
jobs:
  c-clar:
    name: C / Clar
    runs-on: ubuntu-latest

    steps:
      - name: Create test summary
        uses: test-summary/action@v1
        with:
          paths: "*.xml"
        if: always()
