name: Test
on: push

jobs:
  tests:
    name: Run Tests
    runs-on: [self-hosted, linux]
    steps:
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: always()
      with:
        files: |
          tests/*.xml
    
