name: Test
on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          tests/**/*.xml
    - name: SARIF Multitool
      uses: microsoft/sarif-actions@v0.1
      with:
         # Command to be sent to SARIF Multitool
        command: 'validate tests/sarif.sarif'
    - name: SARIF Annotator
      uses: SirYwell/sarif-annotator@v0.1.0
      with:
          report-path: tests/sarif.sarif
