name: Test
on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: '**/*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
          
    
