name: Test
on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Copy Test Results
      if: always()
      run: |
        cp -Lpr /tests tests
      shell: bash
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          tests/*.xml
    
