name: Test
on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          **/*.xml
    - name: Analyze JUnit.xml test report
  # You may pin to the exact commit or the version.
  # uses: tarappo/junit-test-case-analyzer@8f217bfa69dad511b3fb811fb213ca6594562375
      uses: tarappo/junit-test-case-analyzer@v1.1.0
      with:
    # JUnit.xml report path
        junit_report_paths: |
          **/*.xml
          
    
