name: Test
on: push

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          tests/**/*.xml
    - name: SARIF Multitool
      uses: microsoft/sarif-actions@v0.1
      with:
         # Command to be sent to SARIF Multitool
        command: 'validate tests/sarif.sarif'
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tests/sarif.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: my-analysis-tool
